on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: lokpavan03/DemoAug2022/.github/workflows/myaction.yaml@main
        with:
          who-to-greet: 'Siva'
