on: push

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - uses: lokpavan03/DemoAug2022/action.yaml@main
        with:
          who-to-greet: 'Siva'
