name: Reusable Workflow

on:
  push:
  workflow_dispatch:   
jobs:
  call-workflow:
    uses: ../.github/workflows/reusable.yml@main
    secrets:
     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  
     DOCKERTOKEN: ${{ secrets.DOCKERTOKEN }}  
