name: Reusable Workflow

on:
  push:
  workflow_dispatch:   
jobs:
  call-workflow:
    uses: lokpavan03/DemoAug2022/.github/workflows/Main_workflow.yaml@main
    secrets:
     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  
     DOCKERTOKEN: ${{ secrets.DOCKERTOKEN }}  
