# This is a basic workflow to help you get started with Actions

name: Docker Build and Publish Image
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag: 
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERTOKEN:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERTOKEN }}
          
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: devopsdemo4us/demoaug22:latest
          
